default: &default
  rabbitmq:
    sender: gorgmail
    host: localhost
    port: 5672
    vhost: "/"
    queue_name: logs
    deferred_time: 1800000
    exchange_name: "agoram_event_exchange"
    user: guest
    password:


development:
  <<: *default

test:
  <<: *default

production:
  <<: *default