test:
  secret_key_base: 5c470998670700ab03d6be80d36f9907b030fb8e29a0d93d5d272b7d671635d471e31922c099d30f76a56e5fb6b93715a0af43a862c1198cb4cd6cf97e0f5e2a
  gram_api_site: http://api.no-op.gadz.org/api/v2/
  gram_api_user: ratatosk
  gram_api_password: test_pass
  slack_chat_token: abcd-0123456798-0123456789-0123456789-123abc
  slack_chat_channel_id: ABCDEF012
  app_name: Gadzorg RoR Template
  cas_provider_url: auth-nop-op.gadz.org:443
  api_user: user
  api_password: password